language: java

sudo: false

jdk: 
- oraclejdk8

install:
# Build powsybl core
- git clone https://github.com/powsybl/powsybl-core powsybl/powsybl-core
- cd powsybl/powsybl-core && mvn install -DskipTests=true
# Default configuration for powsybl
- mkdir ~/.itools
- echo "LoadFlowFactory=com.powsybl.loadflow.mock.LoadFlowFactoryMock" > ~/.itools/componentDefaultConfig.properties
- cd ${TRAVIS_BUILD_DIR}

after_success:
- mvn jacoco:report coveralls:report
